name: Check Designer profiles

on:
  pull_request:
    paths:
    - 'catalog/designers/*/*'

jobs:
  test_designer_profiles:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
      
    - name: Install dependencies
      run: pip install gftools[qa] pytest
    - name: Check designer profiles
      run: |
        python3 .ci/run.py --pr-number $PR_NUMBER --pr-url-body https://www.github.com/google/fonts/pull/
      env:
        PYTHONIOENCODING: 'utf-8'
        PYTHONUTF8: '1'
        GH_TOKEN: ${{ github.token }}
        PR_NUMBER: ${{ github.event.number }}